
    app:
      build: .
      dockerfile: Dockerfile 
      ports: 
        - "8081:8087"
      links:
        - mongo

    mongo:  
      image: mongo
      volumes: 
        - database:/data/db
      ports: 
        - "27017:27017"
      
    

    
    
    
    
   