# spring:
#    data:
#        mongodb:
#            host: localhost
#            port: 27017
#            database: MongoDB         
#    application:
#        name: TeacherMicroservice
# server:
#  port: 8081